# Default values for zicops-course-query.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxSurge: 1

#Backend image details

image:
  repository: gcr.io/zicops-one/zicops-course-query
  tag: latest
  pullPolicy: Always
  health: /healthz
  port: 8091

maxBodySizeMb: 100
# TODO add more routes for frontend etc..

service:
  type: ClusterIP
  port: 80

zcServiceAccount:
  name: zicops-cc
  secret: zicops-cc
  credential:
    dir: /var/run/secrets/zicops-cc
    file: zicops-cc.json